#!/bin/bash
#Kali source Script
#
#
#

kalSys="abootimg aircrack-ng cewl cgpt crunch dnsrecon dnsutils ethtool exploitdb fake-hwclock \
firefox-esr firmware-atheros firmware-linux firmware-libertas firmware-realtek hydra initramfs-tools john \
libnfc-bin locales-all medusa metasploit-framework mfoc ncrack nmap passing-the-hash proxychains recon-ng \
sqlmap tcpdump theharvester tor tshark u-boot-tools usbutils vboot-utils vboot-kernel-utils \
whois windows-binaries winexe wpscan "
####################################################################################################
kalSysPack="alsa-tools aircrack-ng apache2 armitage autossh \
backdoor-factory bdfproxy beef-xss burpsuite dbd device-pharmer dnsmasq dnsutils dsniff ettercap-text-only\
florence gpsd hostapd isc-dhcp-server iw kismet kismet-plugins libffi-dev libssl-dev macchanger \
mdk3 mitmproxy nishang openssh-server openvpn p0f php pixiewps postgresql ptunnel python-dnspython \
python-lxml python-m2crypto python-mako python-netaddr python-pcapy python-pip python-setuptools\
python-twisted rfkill socat sox sqlmap sslsplit sslstrip tcpdump tcptrace tightvncserver \
tinyproxy tshark wifite wipe wireshark wpasupplicant zip"
# Desktop Packages
kalDMPack="kali-desktop-core desktop-base xfce4 xfce4-goodies xfce4-places-plugin \
xfce4-terminal xfce4-power-manager-plugins gnome-theme-kali lightdm mousepad network-manager-gnome\
xserver-xorg-input-synaptics"
####################################################################################################
# optional packages 
#kalCAW = Advanced Web Attacks and Exploitation
#kalCPW = Penetration Testing with Kali
kalCAWPack="burpsuite firefox-esr impacket-scripts netcat-traditional network-manager-openvpn-gnome \
openjdk-11-jdk-headless python2 rdesktop xfreerdp"

kalCPWPack="apache2 atftpd cewl cherrytree crunch dnsenum dnsrecon dnsutils edb-debugger \
enum4linux exploitdb firefox-esr hash-identifier hydra iptables john medusa metasploit-framework \
mingw-w64 nano nbtscan ncat ncrack net-tools netcat-traditional network-manager-openvpn-gnome \
nmap onesixtyone openjdk-11-jdk-headless openssh-server openvas openvpn passing-the-hash \
proxychains pure-ftpd python recon-ng rinetd sbd snmp snmpcheck sqlmap stunnel4 tcpdump\
theharvester upx-ucl wget whois windows-binaries wine wireshark"
####################################################################################################

#Kali Misc tools
kalMT=$(cat <<EOF
 kali-linux-core
 kali-linux-default
 kali-linux-large
 kali-linux-nethunter
 kali-tools-802-11
 kali-tools-bluetooth
 kali-tools-database
 kali-tools-exploitation
 kali-tools-forensics
 kali-tools-fuzzing
 kali-tools-gpu
 kali-tools-hardware
 kali-tools-headless
 kali-tools-information-gathering
 kali-tools-passwords
 kali-tools-post-exploitation
 kali-tools-reporting
 kali-tools-reverse-engineering
 kali-tools-rfid
 kali-tools-sdr
 kali-tools-sniffing-spoofing
 kali-tools-social-engineering
 kali-tools-crypto-stego
 kali-tools-top10
 kali-tools-voip
 kali-tools-vulnerability
 kali-tools-web
 kali-tools-windows-resources
 kali-tools-wireless
 android-sdk
 device-pharmer
 exploitdb-bin-sploits
 exploitdb-papers
 freeradius
 hackersh
 htshells
 ident-user-enum
 ismtp
 linux-exploit-suggester
 openvas
 parsero
 payloadsallthethings
 python-halberd
 sandi
 set
 shellnoob
 shellter
 teamsploit
 veil
 webhandler
 websploit
 bruteforce-salted-openssl
 brutespray
 capstone-tool
 changeme
 chaosreader
 crack
 dislocker
 goldeneye
 knocker
 nmapsi4
 o-saft
 pnscan
 pompem
 princeprocessor
 shed
 testssl.sh
 wig
EOF)





